const data = {
  mode: 'controller',
  juzamma: [
    {'id':1, 'label': 'An-Naas'},
    {'id':2, 'label': 'Al-Falaq'},
    {'id':3, 'label': 'Al-Ikhlash'},
    {'id':4, 'label': 'Al-Lahb'},
    {'id':5, 'label': 'An-Nashr'},
    {'id':6, 'label': 'Al-Kaafiruun'},
    {'id':7, 'label': 'Al-Kautsar'},
    {'id':8, 'label': 'Al-Maauun'},
    {'id':9, 'label': 'Quraisy'},
    {'id':10, 'label': 'Al-Fiil'},
    {'id':11, 'label': 'Al-Humazah'},
    {'id':12, 'label': 'Al-Ashr'},
    {'id':13, 'label': 'At-Takaatsur'},
    {'id':14, 'label': 'Al-Qaariah'},
    {'id':15, 'label': 'Al-Adiyaat'},
    {'id':16, 'label': 'Az-Zalzalah'},
    {'id':17, 'label': 'Al-Bayyinah'},
    {'id':18, 'label': 'Al-Qadr'},
    {'id':19, 'label': 'Al-Alaq'},
    {'id':20, 'label': 'At-Tiin'},
    {'id':21, 'label': 'As-Syarh'},
    {'id':22, 'label': 'Adh-Dhuha'},
    {'id':23, 'label': 'Al-Lail'},
    {'id':24, 'label': 'Asy-Syams'},
    {'id':25, 'label': 'Al-Balad'},
    {'id':26, 'label': 'Al-Fajr'},
    {'id':27, 'label': 'Al-Ghasyiyah'},
    {'id':28, 'label': 'Al-Alaa'},
    {'id':29, 'label': 'Ath-Thariq'},
    {'id':30, 'label': 'Al-Buruuj'},
    {'id':31, 'label': 'Al-Insyiqaaq'},
    {'id':32, 'label': 'Al-Muthaffifiin'},
    {'id':33, 'label': 'Al-Infithaar'},
    {'id':34, 'label': 'At-Takwiir'},
    {'id':35, 'label': 'Abasa'},
    {'id':36, 'label': 'An-Naaziaat'},
    {'id':37, 'label': 'An-Naba'}],
  animals: [
    {'id': 38,'icon':'🐘','label': 'Gajah'},
    {'id': 39,'icon':'🐑','label': 'Domba'},
    {'id': 40,'icon':'🐄','label': 'Sapi'},
    {'id': 41,'icon':'🐅','label': 'Harimau'},
    {'id': 42,'icon':'🐕','label': 'Anjing'},
    {'id': 44,'icon':'🐈','label': 'Kucing'},
    {'id': 45,'icon':'🐖','label': 'Babi'},
    {'id': 46,'icon':'🐓','label': 'Ayam'},
    {'id': 47,'icon':'🐁','label': 'Tikus'},
    {'id': 48,'icon':'🦖','label': 'T-Rex'},
    {'id': 49,'icon':'🦆','label': 'Bebek'},
    {'id': 50,'icon':'🐦‍⬛','label': 'Gagak'},
    {'id': 51,'icon':'🦅','label': 'Elang'},
    {'id': 52,'icon':'🦉','label': 'Burung Hantu'},
    {'id': 53,'icon':'🐝','label': 'Lebah'},
    {'id': 54,'icon':'🪰','label': 'Lalat'},
    {'id': 55,'icon':'🦟','label': 'Nyamuk'},
    {'id': 56,'icon':'🦗','label': 'Jangkrik'},
    {'id': 57,'icon':'🦍','label': 'Gorilla'},
    {'id': 58,'icon':'🦧','label': 'Orang Utan'},
    {'id': 59,'icon':'🕊️','label': 'Merpati'}
  ],
  vehicles: [
    {'id': 60,'icon':'🚗', 'label': 'Mobil'},
    {'id': 61,'icon':'🏎️', 'label': 'Mobil Balap'},
    {'id': 62,'icon':'🚓', 'label': 'Mobil Polisi'},
    {'id': 63,'icon':'🚑', 'label': 'Ambulans'},
    {'id': 64,'icon':'🚲', 'label': 'Sepeda'},
    {'id': 65,'icon':'🛵', 'label': 'Sepeda Motor'},
    {'id': 66,'icon':'🚂', 'label': 'Kereta'},
    {'id': 67,'icon':'🛩️', 'label': 'Pesawat'},
    {'id': 68,'icon':'🚀', 'label': 'Roket'},
    {'id': 69,'icon':'🚁', 'label': 'Helicopter'},
    {'id': 70,'icon':'🛳️', 'label': 'Perahu'}
  ],
  slider1:0,
  slider2:0,
  connected: false
}